name: "Build with Make"
description: "Build the jobsub_lite RPM using repo makefile"
runs:
  using: "composite"
  steps:
    - name: Install rpm-build
      shell: bash
      run: microdnf install -y rpm-build
    - name: Create RPM directories
      shell: bash
      run: mkdir -p ${HOME}/rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
    - name: Install make
      shell: bash
      run: microdnf install -y make
    - name: Install python3
      shell: bash
      run: microdnf install -y python3
    - name: Run make
      shell: bash
      run: make
    - name: Verify that RPM was generated
      shell: bash
      run: ls -1 jobsub_lite-*.rpm
