#!/bin/sh

. /grid/fermiapp/products/common/etc/setups.sh


#e=samdev
#g=fermilab/volatile

e=nova
g=nova/scratch/users

setup fife_utils v3_2_5
setup hypotcode

srcf=$HYPOTCODE_DIR/fcl/gen_nova.fcl 
ddir=/pnfs/$g/$USER/poms_test/gen_cfg
flist=" 
    c47fe3af-8fdb-4a5a-a110-3f3d52f3cfea-a.fcl
    f6b1e050-4ea4-4045-b45d-190b6715a4ac-b.fcl
    e0d98f93-e5a3-41de-bf2d-207d57ea8b53-c.fcl
    a9d1b4da-74ad-4c4f-8d72-c9e6507531b8-d.fcl
    fa9fff96-99b8-4a97-a0a7-6fb2612f1b46-e.fcl
"

mkdir /tmp/dat$$
cd /tmp/dat$$

checksum=`ifdh checksum $srcf`
filesize=`cat $srcf | wc -c`

cat > a.json <<EOF
{
 "file_name": "c47fe3af-8fdb-4a5a-a110-3f3d52f3cfea-a.fcl", 
 "file_id": 3647554, 
 "create_date": "2016-10-11T15:49:15+00:00", 
 "user": "mengel", 
 "update_date": "2018-09-11T15:30:42+00:00", 
 "update_user": "mengel", 
 "file_size": $filesize, 
 "checksum": $checksum,
 "content_status": "good", 
 "file_type": "unknown", 
 "file_format": "unknown", 
 "end_time": "2016-10-01T00:00:00+00:00", 
 "Dataset.Tag": "gen_cfg", 
 "runs": [
  [
   1, 
   0, 
   "test"
  ]
 ]
}
EOF
cat > b.json <<EOF
{
 "file_name": "f6b1e050-4ea4-4045-b45d-190b6715a4ac-b.fcl", 
 "file_id": 3647704, 
 "create_date": "2016-10-11T15:49:15+00:00", 
 "user": "mengel", 
 "update_date": "2018-09-11T15:30:42+00:00", 
 "update_user": "mengel", 
 "file_size": $filesize, 
 "checksum": $checksum,
 "content_status": "good", 
 "file_type": "unknown", 
 "file_format": "unknown", 
 "end_time": "2016-10-02T00:00:00+00:00", 
 "Dataset.Tag": "gen_cfg", 
 "runs": [
  [
   1, 
   0, 
   "test"
  ]
 ]
}
EOF
cat > c.json <<EOF
{
 "file_name": "e0d98f93-e5a3-41de-bf2d-207d57ea8b53-c.fcl", 
 "file_id": 3647854, 
 "create_date": "2016-10-11T15:49:15+00:00", 
 "user": "mengel", 
 "update_date": "2018-09-11T15:30:42+00:00", 
 "update_user": "mengel", 
 "file_size": $filesize, 
 "checksum": $checksum,
 "content_status": "good", 
 "file_type": "unknown", 
 "file_format": "unknown", 
 "end_time": "2016-10-03T00:00:00+00:00", 
 "Dataset.Tag": "gen_cfg", 
 "runs": [
  [
   2, 
   0, 
   "test"
  ]
 ]
}
EOF
cat > d.json <<EOF
{
 "file_name": "a9d1b4da-74ad-4c4f-8d72-c9e6507531b8-d.fcl", 
 "file_id": 3648004, 
 "create_date": "2016-10-11T15:49:15+00:00", 
 "user": "mengel", 
 "update_date": "2018-09-11T15:30:42+00:00", 
 "update_user": "mengel", 
 "file_size": $filesize, 
 "checksum": $checksum, 
 "content_status": "good", 
 "file_type": "unknown", 
 "file_format": "unknown", 
 "end_time": "2016-10-04T00:00:00+00:00", 
 "Dataset.Tag": "gen_cfg", 
 "runs": [
  [
   2, 
   0, 
   "test"
  ]
 ]
}
EOF
cat > e.json <<EOF
{
 "file_name": "fa9fff96-99b8-4a97-a0a7-6fb2612f1b46-e.fcl", 
 "file_id": 3648154, 
 "create_date": "2016-10-11T15:49:15+00:00", 
 "user": "mengel", 
 "update_date": "2017-11-30T22:41:54+00:00", 
 "update_user": "mengel", 
 "file_size": $filesize, 
 "checksum": $checksum, 
 "content_status": "good", 
 "file_type": "unknown", 
 "file_format": "unknown", 
 "end_time": "2016-10-05T00:00:00+00:00", 
 "Dataset.Tag": "gen_cfg", 
 "runs": [
  [
   3, 
   0, 
   "test"
  ]
 ]
}
EOF

for i in a b c d e; do samweb -e $e declare-file $i.json; done


export IFDH_CP_MAXRETRIES=0
for f in $flist
do
   ifdh cp $srcf $ddir/$f
   samweb -e $e add-file-location $f dcache:$ddir
done

sam_validate_dataset -e $e -n gen_cfg -v

rm -rf /tmp/dat$$
