#!/bin/sh
#
umask 002
# /fife/local/scratch/uploads/fermilab/mengel/2020-04-10_104637.797920_1059/4_20200410_104638_1035333_0_1_wrap.sh
# Automatically generated by: 
#          jobsub -l +JobsubClientDN="/DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Marc Mengel/CN=UID:mengel" -l +JobsubClientIpAddress="131.225.80.97" -l +Owner="mengel" -l +JobsubServerVersion="1.3.1.1" -l +JobsubClientVersion="1.3.1" -l +JobsubClientKerberosPrincipal="mengel@FNAL.GOV" --append_condor_requirements xyz==1 --blacklist FZU --cpu 123 4 --disk 100M -d D --email-to mengel@fnal.gov -e FRED -e JOE=5 --expected-lifetime 567 -f input_1.txt -f input_2.txt --generate-email-summary 1 -L /tmp/submit.log -l +apple=1 -l +orange=2 -Q --mail_on_error --mail_always --maxConcurrent 10 --memory MEMORY -N 2 --OS sl7 --overwrite_condor_requirements abc==2 --resource-provides usage_model=OPPORTUNISTIC,DEDICATED --site Fermigrid --subgroup Silly --tar_file_name tardir:/tmp/stuff --timeout TIMEOUT 3500 1 --verbose 1 /fife/local/scratch/uploads/fermilab/mengel/2020-04-10_104637.797920_1059/printenv 


set_jobsub_debug(){
    export PS4='$LINENO:'
    set -xv
}
[[ "$JOBSUB_DEBUG" ]] && set_jobsub_debug



cleanup_condor_dirs(){
if [[ -d "$_CONDOR_JOB_IWD" ]]; then
   find $_CONDOR_JOB_IWD -mindepth 1 -maxdepth 1 -type d -exec rm -rf {} \;
fi
}


is_set() {
  [ "$1" != "" ]
  RSLT=$?
  return $RSLT
}

get_log_sizes() {
    total=$JOBSUB_MAX_JOBLOG_SIZE
    head=$JOBSUB_MAX_JOBLOG_HEAD_SIZE
    tail=$JOBSUB_MAX_JOBLOG_TAIL_SIZE

    if (( is_set $head) && ( is_set $tail )); then
         total=$(($head + $tail))
    elif ( is_set $total ); then
            if ((  is_set $head ) && (($total > $head))); then
                tail=$(($total - $head))
                total=$((head + tail))
            elif ((  is_set $tail ) && (($total > $tail))); then
                head=$(($total - $tail))
                total=$((head + tail))
            else
                head=$(( $total / 5 ))
                tail=$(( 4 * $total / 5))
            fi
    else
        total=5000000
        head=1000000
        tail=4000000
    fi
    export JOBSUB_MAX_JOBLOG_SIZE=$total
    export JOBSUB_MAX_JOBLOG_HEAD_SIZE=$head
    export JOBSUB_MAX_JOBLOG_TAIL_SIZE=$tail

}

jobsub_truncate() {
    get_log_sizes
    JOBSUB_LOG_SIZE=`wc -c $1 | awk '{print $1}'`
    if ( ! is_set $JSB_TMP );then
            export JSB_TMP=/tmp/$$
        mkdir -p $JSB_TMP
    fi
    JSB_OUT=$JSB_TMP/truncated
    if [ $JOBSUB_LOG_SIZE -gt $JOBSUB_MAX_JOBLOG_SIZE ]; then
        head -c $JOBSUB_MAX_JOBLOG_HEAD_SIZE $1 > $JSB_OUT
        echo "
jobsub:---- truncated after $JOBSUB_MAX_JOBLOG_HEAD_SIZE bytes--
" >>$JSB_OUT
        echo "
jobsub:---- resumed for last $JOBSUB_MAX_JOBLOG_TAIL_SIZE bytes--
" >>$JSB_OUT
        tail -c $JOBSUB_MAX_JOBLOG_TAIL_SIZE $1 >> $JSB_OUT
    else
        cp $1 $JSB_OUT
    fi
    cat $JSB_OUT
    rm $JSB_OUT
}


redirect_output_start(){
    exec 7>&1
    exec >${JSB_TMP}/JOBSUB_LOG_FILE
    exec 8>&2
    exec 2>${JSB_TMP}/JOBSUB_ERR_FILE
}

redirect_output_finish(){
    exec 1>&7 7>&-
    exec 2>&8 8>&-
    jobsub_truncate ${JSB_TMP}/JOBSUB_ERR_FILE 1>&2
    jobsub_truncate ${JSB_TMP}/JOBSUB_LOG_FILE
}


normal_exit(){
    redirect_output_finish
    cleanup_condor_dirs
}

signal_exit(){
    echo "$@ "
    echo "$@ " 1>&2
    exit 255
}


trap normal_exit EXIT
trap "signal_exit received signal TERM"  TERM
trap "signal_exit received signal KILL" KILL
trap "signal_exit received signal ABRT" ABRT
trap "signal_exit received signal QUIT" QUIT
trap "signal_exit received signal ALRM" ALRM
trap "signal_exit received signal INT" INT
trap "signal_exit received signal BUS" BUS
trap "signal_exit received signal PIPE" PIPE

        

setup_ifdh_env(){
#
# create ifdh.sh which runs
# ifdh in a seperate environment to
# keep it from interfering with users ifdh set up
#
cat << '_HEREDOC_' > ${JSB_TMP}/ifdh.sh
#!/bin/sh
#
which ifdh > /dev/null 2>&1
has_ifdh=$?
if [ "$has_ifdh" -ne "0" ] ; then
    unset PRODUCTS
    for setup_file in /cvmfs/fermilab.opensciencegrid.org/products/common/etc/setups /grid/fermiapp/products/common/etc/setups.sh /fnal/ups/etc/setups.sh ; do
      if [ -e "$setup_file" ] && [ "$has_ifdh" -ne "0" ]; then
         source $setup_file
         ups exist ifdhc $IFDH_VERSION
         has_ifdh=$?
         if [ "$has_ifdh" = "0" ] ; then
             setup ifdhc $IFDH_VERSION
             break
         else
            unset PRODUCTS
         fi
     fi
   done
fi
which ifdh > /dev/null 2>&1
if [ "$?" -ne "0" ] ; then
    echo "Can not find ifdh version $IFDH_VERSION ,exiting!"
    echo "Can not find ifdh version $IFDH_VERSION ,exiting! ">&2
    exit 1
else
    ifdh "$@"
    exit $?
fi
_HEREDOC_
chmod +x ${JSB_TMP}/ifdh.sh
}
            

#############################################################
# main ()                                                     #
###############################################################
touch .empty_file
# Hold and clear arg list
args="$@"
set - ""
[[ "$JOBSUB_DEBUG" ]] && set_jobsub_debug

export JSB_TMP=$_CONDOR_SCRATCH_DIR/jsb_tmp
mkdir -p $JSB_TMP
export _CONDOR_SCRATCH_DIR=$_CONDOR_SCRATCH_DIR/no_xfer
export TMP=$_CONDOR_SCRATCH_DIR
export TEMP=$_CONDOR_SCRATCH_DIR
export TMPDIR=$_CONDOR_SCRATCH_DIR
mkdir -p $_CONDOR_SCRATCH_DIR
export CONDOR_DIR_INPUT=${_CONDOR_SCRATCH_DIR}/${PROCESS}/TRANSFERRED_INPUT_FILES
mkdir -p $CONDOR_DIR_INPUT
redirect_output_start

setup_ifdh_env
export PATH="${PATH}:."


export JOBSUB_EXE_SCRIPT=$(ls 4 2>/dev/null)
if [ "$JOBSUB_EXE_SCRIPT" = "" ]; then 
     export JOBSUB_EXE_SCRIPT=$(find . -name 4 -print | head -1)
fi
chmod +x $JOBSUB_EXE_SCRIPT
${JSB_TMP}/ifdh.sh log "mengel:$JOBSUBJOBID BEGIN EXECUTION $JOBSUB_EXE_SCRIPT  --disk 100M -d D --email-to mengel@fnal.gov -e FRED -e JOE=5 --expected-lifetime 567 -f input_1.txt -f input_2.txt --generate-email-summary 1 -L /tmp/submit.log -l +apple=1 -l +orange=2 -Q --mail_on_error --mail_always --maxConcurrent 10 --memory MEMORY -N 2 --OS sl7 --overwrite_condor_requirements abc==2 --resource-provides usage_model=OPPORTUNISTIC,DEDICATED --site Fermigrid --subgroup Silly --tar_file_name tardir:/tmp/stuff --timeout TIMEOUT 3500 1 --verbose 1 /fife/local/scratch/uploads/fermilab/mengel/2020-04-10_104637.797920_1059/printenv  
 "


export NODE_NAME=`hostname`
export BOGOMIPS=`grep bogomips /proc/cpuinfo | tail -1 | cut -d ' ' -f2`
export VENDOR_ID=`grep vendor_id /proc/cpuinfo | tail -1 | cut -d ' ' -f2`
export poms_data='{"campaign_id":"'$CAMPAIGN_ID'","task_definition_id":"'$TASK_DEFINITION_ID'","task_id":"'$POMS_TASK_ID'","job_id":"'$POMS_JOB_ID'","batch_id":"'$JOBSUBJOBID'","host_site":"'$HOST_SITE'","bogomips":"'$BOGOMIPS'","node_name":"'$NODE_NAME'","vendor_id":"'$VENDOR_ID'"}'

        
${JSB_TMP}/ifdh.sh log poms_data=$poms_data
echo `date` $JOBSUBJOBID BEGIN EXECUTION $JOBSUB_EXE_SCRIPT  --disk 100M -d D --email-to mengel@fnal.gov -e FRED -e JOE=5 --expected-lifetime 567 -f input_1.txt -f input_2.txt --generate-email-summary 1 -L /tmp/submit.log -l +apple=1 -l +orange=2 -Q --mail_on_error --mail_always --maxConcurrent 10 --memory MEMORY -N 2 --OS sl7 --overwrite_condor_requirements abc==2 --resource-provides usage_model=OPPORTUNISTIC,DEDICATED --site Fermigrid --subgroup Silly --tar_file_name tardir:/tmp/stuff --timeout TIMEOUT 3500 1 --verbose 1 /fife/local/scratch/uploads/fermilab/mengel/2020-04-10_104637.797920_1059/printenv  
>&2 echo `date` $JOBSUBJOBID BEGIN EXECUTION $JOBSUB_EXE_SCRIPT  --disk 100M -d D --email-to mengel@fnal.gov -e FRED -e JOE=5 --expected-lifetime 567 -f input_1.txt -f input_2.txt --generate-email-summary 1 -L /tmp/submit.log -l +apple=1 -l +orange=2 -Q --mail_on_error --mail_always --maxConcurrent 10 --memory MEMORY -N 2 --OS sl7 --overwrite_condor_requirements abc==2 --resource-provides usage_model=OPPORTUNISTIC,DEDICATED --site Fermigrid --subgroup Silly --tar_file_name tardir:/tmp/stuff --timeout TIMEOUT 3500 1 --verbose 1 /fife/local/scratch/uploads/fermilab/mengel/2020-04-10_104637.797920_1059/printenv  
$JOBSUB_EXE_SCRIPT --disk 100M -d D --email-to mengel@fnal.gov -e FRED -e JOE=5 --expected-lifetime 567 -f input_1.txt -f input_2.txt --generate-email-summary 1 -L /tmp/submit.log -l +apple=1 -l +orange=2 -Q --mail_on_error --mail_always --maxConcurrent 10 --memory MEMORY -N 2 --OS sl7 --overwrite_condor_requirements abc==2 --resource-provides usage_model=OPPORTUNISTIC,DEDICATED --site Fermigrid --subgroup Silly --tar_file_name tardir:/tmp/stuff --timeout TIMEOUT 3500 1 --verbose 1 /fife/local/scratch/uploads/fermilab/mengel/2020-04-10_104637.797920_1059/printenv   
JOB_RET_STATUS=$?
echo `date` $JOBSUB_EXE_SCRIPT COMPLETED with exit status $JOB_RET_STATUS
echo `date` $JOBSUB_EXE_SCRIPT COMPLETED with exit status $JOB_RET_STATUS 1>&2
${JSB_TMP}/ifdh.sh log "$JOBSUBJOBID mengel:4 COMPLETED with return code $JOB_RET_STATUS" 
exit $JOB_RET_STATUS
