.TH UF "1" "Sep 2022" "jobsub_hold " "jobsub_lite script jobsub_hold"
.SH NAME
jobsub_hold

.SH USAGE
 jobsub_hold [-h] [-G GROUP] [--role ROLE] [--subgroup SUBGROUP]
                   [--verbose] [-J JOBID] [-name NAME]
                   [--jobsub_server JOBSUB_SERVER]
                   [job_id]

.SH DESCRIPTION
A part of the jobsub_lite suite, jobsub_hold puts jobs submitted by jobsub_submit into the HELD state where they will not run until they are released with jobsub_release.

.SH OPTIONS
positional arguments:
  job_id                job/submission ID

optional arguments:
.HP
  -h, --help            show this help message and exit
.HP
  -J JOBID, --jobid JOBID
                        job/submission ID
.HP
  -name NAME            Set schedd name
.HP
  --jobsub_server JOBSUB_SERVER
                        backwards compatability; ignored

general arguments:
.HP
  -G GROUP, --group GROUP
                        Group/Experiment/Subgroup for priorities and
                        accounting
.HP
  --role ROLE           VOMS Role for priorities and accounting
.HP
  --subgroup SUBGROUP   Subgroup for priorities and accounting. See
                        https://cdcvs.fnal.gov/redmine/projects/jobsub/wiki/
                        Jobsub_submit#Groups-Subgroups-Quotas-Priorities for
                        more documentation on using --subgroup to set job
                        quotas and priorities
.HP
  --verbose             dump internal state of program (useful for debugging)

also condor_hold arguments: [options] [constraints]
(with single '-' or double '--' dashes)
 where [options] is zero or more of:
.HP
  -help               Display this message and exit
.HP
  -version            Display version information and exit
.HP
  -long               Display full result classad
.HP
  -totals             Display success/failure totals
.HP
  -name schedd_name   Connect to the given schedd
.HP
  -pool hostname      Use the given central manager to find daemons
.HP
  -addr <ip:port>     Connect directly to the given "sinful string"
.HP
  -reason reason      Use the given HoldReason
.HP
  -subcode number     Set HoldReasonSubCode
 and where [constraints] is one of:
  cluster.proc        Hold the given job
  cluster             Hold the given cluster of jobs
  user                Hold all jobs owned by user
.HP
  -constraint expr    Hold all jobs matching the boolean expression
.HP
  -all                Hold all jobs (cannot be used with other constraints)
