name: "Prepare AL9 container with jobsub_lite and jobsub_lite_config repos"
description: "Install needed dependencies and checkout jobsub_lite and jobsub_lite_config repositories"
runs:
  using: "composite"
  steps:
    - name: Install tar and gzip
      shell: bash
      run: |
        microdnf install -y tar
        microdnf install -y gzip
    - name: Check out jobsub_lite in runner
      uses: actions/checkout@v4
    - name: Check out jobsub_lite_config in runner
      uses: actions/checkout@v4
      with:
        repository: fermitools/jobsub_lite_config
        path: config
        token: ${{ secrets.ACCESS_JOBSUB_LITE_CONFIG }}
