name: build-sl7-push

on:
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  pushed_commit:
    runs-on: ubuntu-20.04
    name: "Build master after push in SL7 container"
    container:
      image: scientificlinux/sl:7
    steps:
      - name: Check out jobsub_lite in runner
        uses: actions/checkout@v3
      - name: Check out jobsub_lite_config in runner
        uses: actions/checkout@v3
        with:
          repository: fermitools/jobsub_lite_config
          path: config
          token: ${{ secrets.ACCESS_JOBSUB_LITE_CONFIG }}
      - uses: ./.github/actions/build-with-make-sl7
