name: build-al9

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  pr_merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: "Build master with merged PR in AL9 container"
    container:
      image: almalinux:9.3-minimal
    steps:
      - uses: ./.github/actions/prepare-al9-container-with-repo
      - uses: ./.github/actions/build-with-make
  pushed_commit:
    runs-on: ubuntu-latest
    name: "Build master after push in AL9 container"
    container:
      image: almalinux:9.3-minimal
    steps:
      - uses: ./.github/actions/prepare-al9-container-with-repo
      - uses: ./.github/actions/build-with-make
