name: pylint

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  run_pylint:
    runs-on: ubuntu-20.04
    env:
      pylint_version: 2.13.9
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.6 (until SL7 is gone)
      uses: actions/setup-python@v3
      with:
        python-version: 3.6.8
    - name: Install pylint
      run: |
        python3 -m pip install --upgrade pip
        pip install pylint==$pylint_version
    - name: Run pylint on code (lib)
      run: pylint --rcfile=.pylintrc lib/*
    - name: Run pylint on code (bin)
      run: pylint --rcfile=.pylintrc --ignore=condor_vault_storer bin/*
